// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA86UtnhiKwJwmANcw__FZ6psDOrUXKcDs',
    appId: '1:973785434817:web:603ac83d3adc02ce27e240',
    messagingSenderId: '973785434817',
    projectId: 'ecommerce-d1fae',
    authDomain: 'ecommerce-d1fae.firebaseapp.com',
    storageBucket: 'ecommerce-d1fae.appspot.com',
    measurementId: 'G-LF4P30ERPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXFAX68aGDpQoybvceHm7NqWjIitIjSxM',
    appId: '1:973785434817:android:b03772ba15ad3bd727e240',
    messagingSenderId: '973785434817',
    projectId: 'ecommerce-d1fae',
    storageBucket: 'ecommerce-d1fae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArwnh14VslSXE-Phg0AIAekushBQ_AxLo',
    appId: '1:973785434817:ios:fa29460cdfab1ca727e240',
    messagingSenderId: '973785434817',
    projectId: 'ecommerce-d1fae',
    storageBucket: 'ecommerce-d1fae.appspot.com',
    iosClientId: '973785434817-2i6nrpgpcjfj97evp9gimu3vjh1kqusa.apps.googleusercontent.com',
    iosBundleId: 'com.example.first',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArwnh14VslSXE-Phg0AIAekushBQ_AxLo',
    appId: '1:973785434817:ios:fa29460cdfab1ca727e240',
    messagingSenderId: '973785434817',
    projectId: 'ecommerce-d1fae',
    storageBucket: 'ecommerce-d1fae.appspot.com',
    iosClientId: '973785434817-2i6nrpgpcjfj97evp9gimu3vjh1kqusa.apps.googleusercontent.com',
    iosBundleId: 'com.example.first',
  );
}
